### ISSUE TITLE
Ignore Internet explorer browser

### ISSUE THREAD

**Issue by NaorYael** [browserslist/browserslist-useragent-regexp#1049]
Is there any why to Ignore Internet Explorer browser?

**Comment by dangreen** [comment]
@NaorYael Hi. Could you please explain what you mean?

**Comment by phcorp** [comment]
you should be able to achieve that by adding `not IE` in `.browserlistrc` (see: https://browserslist.dev/?q=PiAwLjI1JSBpbiBGUiwgbGFzdCAyIHZlcnNpb25zLCBGaXJlZm94IEVTUiwgbm90IGRlYWQsIG5vdCBJRSAxMQ%3D%3D)

unfortunately it does not seem to be taken into account by this package

**Comment by dangreen** [comment]
You should use `not ie > 0, not ie_mob > 0` to exclude all IE browsers.

**Comment by ELFrontEnd** [comment]
> You should use `not ie > 0, not ie_mob > 0` to exclude all IE browsers.

Have you tested it ?

Just did it and it does not work when you use the `.browserlistrc` implementation.
You still get this part in the generated regexp:
`(([MS]?IE) (11|(1[2-9]|[2-9]\d|\d{3,}))\.\d+)`

**Comment by dangreen** [comment]
@ELFrontEnd 
https://codesandbox.io/s/keen-jang-lbtvb?file=/.browserslistrc
<img width="1627" alt="Снимок экрана 2022-01-07 в 00 35 51" src="https://user-images.githubusercontent.com/986756/148425875-b53ea179-5219-4d50-9dc3-51636ac82454.png">

**Comment by ELFrontEnd** [comment]
Headache because of a typo `.browserlistrc` => `.browserslistrc`
