### ISSUE TITLE
Chrome iPhone/iPad detection: desktop mode

### ISSUE THREAD

**Issue by phcorp** [browserslist/browserslist-useragent-regexp#1109]
**Description**

Currently generated regex does not detect chrome on iPhone/iPad in desktop mode.

**Steps to reproduce**

1. use regex generated by browserslist-useragent-regexp in chrome on iPhone/iPad: browser is detected
2. use regex generated by browserslist-useragent-regexp in chrome on iPhone/iPad in desktop mode: browser is not detected

Desktop mode can be selected in menu in chrome app.

**Additional information**

ios version: latest (`15.2.1`)

chrome version used: latest (`v98.0.4758.85`)

.browserslistrc:
```
> 0.1% in my stats # see browserlist-stats.json
last 2 versions
Firefox ESR
not dead
not IE 11
unreleased versions
```

regex: `/((CPU[ +]OS|iPhone[ +]OS|CPU[ +]iPhone|CPU IPhone OS)[ +]+(12|(1[3-9]|[2-9]\d|\d{3,})|13|(1[4-9]|[2-9]\d|\d{3,})|14|(1[5-9]|[2-9]\d|\d{3,})|15|(1[6-9]|[2-9]\d|\d{3,}))[_.]\d+(?:[_.]\d+)?)|(Opera Mini(?:\/att)?\/?(\d+)?(?:\.\d+)?(?:\.\d+)?)|(Opera\/.+Opera Mobi.+Version\/(64|(6[5-9]|[7-9]\d|\d{3,}))\.\d+)|(Opera\/(64|(6[5-9]|[7-9]\d|\d{3,}))\.\d+.+Opera Mobi)|(Opera Mobi.+Opera(?:\/|\s+)(64|(6[5-9]|[7-9]\d|\d{3,}))\.\d+)|((?:Chrome).*OPR\/(81|(8[2-9]|9\d|\d{3,}))\.\d+\.\d+)|(SamsungBrowser\/(14|(1[5-9]|[2-9]\d|\d{3,}))\.\d+)|(Edge\/(95|(9[6-9]|\d{3,}))(?:\.\d+)?)|((Chromium|Chrome)\/(94|(9[5-9]|\d{3,}))\.\d+(?:\.\d+)?)|(Version\/(13|(1[4-9]|[2-9]\d|\d{3,})|14|(1[5-9]|[2-9]\d|\d{3,})|15|(1[6-9]|[2-9]\d|\d{3,}))\.\d+(?:\.\d+)? Safari\/)|(Firefox\/(78|(79|[8-9]\d|\d{3,})|91|(9[2-9]|\d{3,})|93|(9[4-9]|\d{3,}))\.\d+\.\d+)|(Firefox\/(78|(79|[8-9]\d|\d{3,})|91|(9[2-9]|\d{3,})|93|(9[4-9]|\d{3,}))\.\d+(pre|[ab]\d+[a-z]*)?)/`

user-agent: `Mozilla/5.0 (iPad; CPU OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/98.0.4758.85 Mobile/15E148 Safari/604.1`

user-agent (dektop mode): `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/98 Version/11.1.1 Safari/605.1.15`

**Comment by dangreen** [comment]
@phcorp Hi!

Looks like in desktop mode this browser wants to be like Safari 11, but your query covers only Safari >= 13

**Comment by phcorp** [comment]
Hi Dan! Thanks for you response. It looks like the version put by chrome in the user-agent string (in desktop mode) is quite different of what is expected from safari, for instance on the same device:

safari user-agent: `Mozilla/5.0 (iPad; CPU OS 15_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1`

safari user-agent (desktop mode): `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15`

chrome implementation seems a little bizarre (I don't know to what the version number is related to) ; I reported an issue through the app but I was not given a link to share here, I will post it here if provided later.

**Comment by phcorp** [comment]
Fixed in chrome mobile, no tracking link was provided
