### ISSUE TITLE
API call `getUserAgentRegExps` doesn't provide default for browsers

### ISSUE THREAD

**Issue by JKirchartz** [browserslist/browserslist-useragent-regexp#139]
The documentation says the `browsers` option of  `getUserAgentRegExps`

> Manually provide a browserslist query (or an array of queries). Specifying this overrides the browserslist configuration specified in your project.

Which implies that it checks the `package.json` for this information; however running `getUserAgentRegExps()` results in an error: `Uncaught TypeError: Cannot read property 'browsers' of undefined` 

Shouldn't `browsers` default to package.json's browserslist?

**Comment by dangreen** [comment]
@JKirchartz 

https://github.com/browserslist/browserslist-useragent-regexp/blob/8839e17/src/useragentRegexp/useragentRegexp.ts#L35

`getUserAgentRegExps` has required first argument

**Comment by JKirchartz** [comment]
I see that, but how could the required argument override the "browserslist configuration specified in your project" if it never fetches the browserslist configuration specified in my project?

Shouldn't the `browsers` option have a default value sourced from the root project's `package.json` or `.browserslistrc` file before that default could be overridden?

**Comment by dangreen** [comment]
@JKirchartz  `getUserAgentRegExps` calls [`browserslist`](https://github.com/browserslist/browserslist#js-api) inside, which looks for config files.

**Comment by JKirchartz** [comment]
I "get it" now - you've gotta call `getUserAgentRegExp({})` for it to automatically detect the settings

**Comment by dangreen** [comment]
@JKirchartz in v1.3.2 you can call `getUserAgentRegExp()` without argument
