### ISSUE TITLE
Support both esm and cjs

### ISSUE THREAD

**Issue by kingyue737** [browserslist/browserslist-useragent-regexp#1460]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Hi, firstly, thanks for this nice library.
CJS is still more widely used than ESM. I think it may not be a good idea to drop support for CJS. I wrapped `browserslist-useragent-regexp` in a vite plugin. This breaking change will force users to use `vite.config.mts` instead of `vite.config.ts` while all the other vite plugins support CJS.

### Describe the solution you'd like

Generate entry points for both ESM and CJS with rollup

**Comment by dangreen** [comment]
@kingyue737 Hi. Today many packages have become ESM-only. It is important to push forward ESM adoption. 

In your case you can use dynamic import:

```js
    async load(id) {
      if (id === resolvedVirtualModuleId) {
        const {
          getUserAgentRegex,
          getUserAgentRegexes,
        } = await import('browserslist-useragent-regexp')

        return `export const browsersRegex = ${getUserAgentRegex(options)}
export const browsersRegexes = ${JSON.stringify(getUserAgentRegexes(options))}`
      }
    }
```

**Comment by rake7h** [comment]
I'm getting No "exports" main defined with dynamic import. What I'm missing? @dangreen 

![Screenshot 2023-06-07 at 4 50 50 PM](https://github.com/browserslist/browserslist-useragent-regexp/assets/18216179/6dae2644-515b-4244-9870-668192aeae69)

**Comment by rake7h** [comment]
@dangreen  https://github.com/rake7h/react-ssr-template/pull/2/files added the browserslist-useragent-regexp to one of my example react-ssr express app. Have a look.
