### ISSUE TITLE
[Bug]: JS API export broken in 4.0.0

### ISSUE THREAD

**Issue by BATCOH** [browserslist/browserslist-useragent-regexp#1464]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

In sandbox:
```
ModuleNotFoundError
Could not find module in path: 'browserslist-useragent-regexp' relative to '/src/index.js'
```

In my project after upgrade from 3.0.2:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Projects/front/node_modules/browserslist-useragent-regexp/package.json
```

### Reproduction

https://codesandbox.io/s/browserslist-useragent-regexp-import-bug-d3u7f7

### browserslist-useragent-regexp version

v4.0.0

### Possible solution

The `main` field was removed from package.json in [41456bc](https://github.com/browserslist/browserslist-useragent-regexp/commit/41456bc22b789fee57384a00abb64e0690ded08a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L17).

Maybe it should be returned?

**Comment by dangreen** [comment]
@BATCOH Hi. browserslist-useragent-regexp v4 is an ESM-package only. To use it in your project it also should be an ES module:

```json
// package.json
{
  "type": "module"
}
```

Or you can use dynamic `import` to import ES module from commonjs module.

**Comment by BATCOH** [comment]
Thank you! Dynamic import solved my problem.
