### ISSUE TITLE
[Bug]: cannot install on macOS

### ISSUE THREAD

**Issue by alejandroiglesias** [browserslist/browserslist-useragent-regexp#1471]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I see an error from npm when installing the newer 4.0 version due to the inotify library requiring Linux as the OS.
```
❯ npm install --save=dev browserslist-useragent-regexp
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```
This is blocking me from trying the new version with the new regexes which I look forward to since the 3.x version generates a regex that leaves out iPad/iPod.

### Reproduction

Run `npm install --save=dev browserslist-useragent-regexp` on macOS

### browserslist-useragent-regexp version

4.0.0

### Possible solution

Probably use a different, cross-platform library for detecting OS filesystem events.

**Comment by dangreen** [comment]
@alejandroiglesias Hi. `browserslist-useragent-regexp` don't have inotify package in dependencies. Please check your package.json and dependencies.

```bash
github$ mkdir test
github$ cd test
test$ echo "{}" > package.json
test$ npm i -D browserslist-useragent-regexp

added 16 packages, and audited 17 packages in 4s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
test$ sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
test$ npm why inotify
npm ERR! No dependencies found matching inotify

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dangreen/.npm/_logs/2022-12-07T17_09_01_096Z-debug-0.log
test$ 
```
