### ISSUE TITLE
[Bug]: Chrome on iPad OS 16 not matching defaults

### ISSUE THREAD

**Issue by dandormont** [browserslist/browserslist-useragent-regexp#1478]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I have a user accessing my site from Chrome on an iPad Pro with iOS 16. This flavor of Chrome offers both a "Desktop" and "Mobile" view, and they reported that in the former mode, it uses the following user-agent:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/111 Version/11.1.1 Safari/605.1.15`

This does not match the "defaults" configuration in browserslist-useragent-regex with the latest version. I created a codesandbox to reproduce this. It matches fine with Chrome on my Mac desktop.

As far as I can tell, browserslist-useragent itself does match that UA, but I am not able to use browserlist-useragent directly on my site, so I am looking to have it work with browserslist-useragent-regexp.

### Reproduction

https://codesandbox.io/s/stoic-lamport-uhogif?file=/src/index.js

### browserslist-useragent-regexp version

v4.0.0

**Comment by dangreen** [comment]
@dandormont Hi. Browserslist has different queries for Desktop Safari and Mobile Safari (iOS). Chrome on iOS is actually Mobile Safari. Safari on iPad Pro by default gives desktop useragent, so it will be detected as Desktop Safari.

<img width="1289" alt="Снимок экрана 2023-03-20 в 22 57 27" src="https://user-images.githubusercontent.com/986756/226441310-de33c342-58bf-4be1-8ea4-c62bfaddb947.png">

Chrome on iOS by default gives mobile useragent - it will be detected as Safari iOS

<img width="1295" alt="Снимок экрана 2023-03-20 в 22 59 27" src="https://user-images.githubusercontent.com/986756/226441854-2db7582a-85d0-4ff5-8b67-8b5b1c5e1ebb.png">

If you request "desktop site", Chrome gives you desktop useragent, but with old Safari version, which is not in "default" browserslist query.

<img width="1261" alt="Снимок экрана 2023-03-20 в 22 56 54" src="https://user-images.githubusercontent.com/986756/226442125-e8268bfe-a8a4-4fe6-9e52-f55a16ec5380.png">

**Comment by dandormont** [comment]
@dangreen thanks for the response. So is there any way to get the regexp to match when "desktop site" is requested? It's obviously not really Safari 11.x
