### ISSUE TITLE
[Bug]: Version 4 is missing `main` in the package.json

### ISSUE THREAD

**Issue by Akrion** [browserslist/browserslist-useragent-regexp#1493]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

In version `3.0.0` there was `"main": "lib/index.js",` in the `package.json`
in version `4.0.0` `main` is missing and it is causing issues wit ESLint

### Reproduction

Do we really need one?

### browserslist-useragent-regexp version

4.0.0

### Possible solution

Add `main` to `package.json`

**Comment by dangreen** [comment]
@Akrion Hi. browserslist-useragent-regexp is a modern packages and it uses "exports" field.

**Comment by dangreen** [comment]
@Akrion Hi. browserslist-useragent-regexp is a modern packages and it uses "exports" field.
