### ISSUE TITLE
[Bug]: Types error after "types": "./dist/index.d.ts" removal from package.json

### ISSUE THREAD

**Issue by tomek-f** [browserslist/browserslist-useragent-regexp#1545]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

After 4.1.2 update: 
* NPM does not show blue types icon (`This package contains built-in TypeScript declarations`)
* Typescript whines about types ```TS2307: Cannot find module 'browserslist-useragent-regexp' or its corresponding type declarations.
  There are types at '/Users/xyz/Workspace/abc/node_modules/browserslist-useragent-regexp/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.```
  
Changing moduleResolution from `node` to 'node16', 'nodenext', or 'bundler', opens another can of worms in my project.

I believe it's this change: https://github.com/browserslist/browserslist-useragent-regexp/commit/f0146127ac364a70a42bfc442c7f5aef3073bd2e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L33 

Was this change intentional?

4.1.1 https://www.npmjs.com/package/browserslist-useragent-regexp/v/4.1.1?activeTab=code
4.1.2 https://www.npmjs.com/package/browserslist-useragent-regexp/v/4.1.2?activeTab=code

### Reproduction

N/A

### browserslist-useragent-regexp version

v4.1.2

### Possible solution

* bring back `"types": "./dist/index.d.ts"` part

**Comment by dangreen** [comment]
[v4.1.3](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v4.1.3)

**Comment by flying-sheep** [comment]
Hm, according to npmjs.com’s [RFC 46](https://github.com/npm/rfcs/blob/6f61e5a2394040fa5843024d799db4ac675378d5/implemented/0046-add-types-metadata-to-package-json.md) and [TypeScript 4.7’s docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing), leaving out `types` shouldn’t have caused either of these effects.
