### ISSUE TITLE
[Bug]: "firefox >= 124" produces nothing

### ISSUE THREAD

**Issue by IanBellomy** [browserslist/browserslist-useragent-regexp#1548]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Current: `npx browserslist-useragent-regexp "firefox >= 124"` (or 125) produces  `/(?:)/;`.
Expected output: `/Firefox\/(12[4-9]|1[3-9]\d|[2-9]\d\d|\d{4,})\.\d+(\.\d+|)/; `

### Reproduction

npx browserslist-useragent-regexp "firefox >= 124"

### browserslist-useragent-regexp version

^4.1.3

**Comment by dangreen** [comment]
@IanBellomy Hi. Please [update browserslist db](https://github.com/browserslist/update-db).
