### ISSUE TITLE
False positive on Edge 17 when Chrome >= 51 is present

### ISSUE THREAD

**Issue by dimitarnestorov** [browserslist/browserslist-useragent-regexp#23]
Our website doesn't work on Edge 17 but the regex would say otherwise.
Here's a minimal browserslist config that should return false on Edge 17, but is true:
```json
[
    "chrome >= 51",
    "edge >= 18"
]
```
Omitting the Chrome line returns false.

**Comment by dimitarnestorov** [comment]
Not sure if you have access to Edge 17, here's it's `userAgent`:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
```

**Comment by dangreen** [comment]
@dimitarnestorov 

> ```
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
> ```

`Chrome/64.0.3282.140` is `chrome >= 51`

**Comment by dangreen** [comment]
Edge user agent is strange...

**Comment by dimitarnestorov** [comment]
That's right Edge reports Chrome 64 so that libraries like yours wouldn't discard it as an unsupported browser. The actual engine that the browser uses isn't Chromium yet but is [EdgeHTML](https://en.wikipedia.org/wiki/EdgeHTML). I still remember how browser detection websites reported Edge as Chrome when it just came out. And also it had bugs that only IE 11 had.

**Comment by dangreen** [comment]
@dimitarnestorov ok, I need some time to think about some workaround for Edge ua.

**Comment by dangreen** [comment]
@dimitarnestorov 

Please try [demo](https://browserslist.github.io/browserslist-useragent-regexp/demo.html) and report about results. After your confirmation I will publish new release.

Explanation:

If browserslist query contains Chrome < 74 and Edge <= 18, patch will be applied to Chrome regexp.

1) Last ever (?) EdgeHTML version is 18 (https://en.wikipedia.org/wiki/Microsoft_Edge)
2) First known Chromium Edge has Chrome 74 version (https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/#HzAbspiQ4poHQRVc.97)

**Comment by dimitarnestorov** [comment]
Edge 17:
![image](https://user-images.githubusercontent.com/8790386/57455223-58e94980-7273-11e9-961b-ebc18198236f.png)
Edge 18:
![image](https://user-images.githubusercontent.com/8790386/57455122-1a538f00-7273-11e9-84a1-355b8c3eda13.png)
Edge Chromium 75 (notice how it says Edg instead of Edge):
![image](https://user-images.githubusercontent.com/8790386/57455162-348d6d00-7273-11e9-9e9a-57c74d02990c.png)

**Comment by dangreen** [comment]
> Edge Chromium 75 (notice how it says Edg instead of Edge):

Anyway, all Chrome-based browsers should be detected as Chrome.

**Comment by dangreen** [comment]
[v1.2.0-beta](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v1.2.0-beta)

**Comment by dimitarnestorov** [comment]
Just tested it, works. Thank you!
