### ISSUE TITLE
CLI parses the wrong option for --ignoreMinor

### ISSUE THREAD

**Issue by pucka** [browserslist/browserslist-useragent-regexp#232]
In the documentation and everywhere in the code the option `ignoreMinor` is used. Except for the option-parser in the cli code. There instead it looks for the option `ignoreMajor`. This make it impossible to set the `--ignoreMinor` option.  All you get is the `Unexpected key "ignoreMinor"` error message.

I guess this is just a typo and should be easy to fix.

**Comment by dangreen** [comment]
Hi @pucka , thanks for issue! You can check fix in [v1.3.3](https://www.npmjs.com/package/browserslist-useragent-regexp/v/1.3.3-beta)

**Comment by pucka** [comment]
Works like a charm, thx for the quick fix!
