### ISSUE TITLE
BrowserslistError: Unknown browser Explorer_mob

### ISSUE THREAD

**Issue by PaulBlanche** [browserslist/browserslist-useragent-regexp#261]
There is an issue with passing `ie_mob 11` as a query, which is transformed to `Explorer_mob 11`.
It seems there was a similar issue in browserslist-useragent wich was fixed: https://github.com/browserslist/browserslist-useragent/issues/35

**Comment by dangreen** [comment]
@PaulBlanche Hi! Please try browserslist-useragent-regexp@1.3.4-beta

**Comment by PaulBlanche** [comment]
Hi, thanks for the quick fix ! It seems to be working.
