### ISSUE TITLE
Instructions don't appear to work on Windows dev machines

### ISSUE THREAD

**Issue by shiraze** [browserslist/browserslist-useragent-regexp#36]
The contents of the supportedBrowsers.js file created when `npm run supportedBrowsers` is run on a Windows PC is:
`
"module.exports = $(browserslist-useragent-regexp --allowHigherVersions);" 
`

That is, no substitution takes place

**Comment by dangreen** [comment]
@shiraze 

Hi, thank you for issue.

Can you help with it? How it should works on Windows PC?

**Comment by shiraze** [comment]
@dangreen I'm not sure how substitution is meant to happen in package.json files on a PC! I'm still researching. What I can say, though, is that I can run `px browserslist-useragent-regexp --allowHigherVersions > supportedBrowsers.js` to get a suitable RegEx in the file specified.

**Comment by shiraze** [comment]
The problem appears to be lack of support from npm for command substitution in package,json on Windows.

**Comment by dangreen** [comment]
@shiraze 

you can try this:

```json
{
  "scripts": {
    "supportedBrowsers": "echo \"module.exports = \" > supportedBrowsers.js; browserslist-useragent-regexp --allowHigherVersions >> supportedBrowsers.js"
  }
}
```

**Comment by shiraze** [comment]
@dangreen , the output from the above is:
`
"module.exports = $(browserslist-useragent-regexp --allowHigherVersions);" 
"module.exports = " ; browserslist-useragent-regexp --allowHigherVersions 
`

Windows CMD just doesn't want to substitute properly.
Even running `npm run supportedBrowsers` from a virtualised bash terminal doesn't work - I'm using VSCode for development on Windows, and can use the "Git bash" as a shell

**Comment by shiraze** [comment]
I think for now I'm just going to stick to using "npx", and hold my breath for command substitution on Windows.

**Comment by dangreen** [comment]
@shiraze can you share screenshot of output / output file for `npm run supportedBrowsers`
with 
```json
{
  "scripts": {
    "supportedBrowsers": "echo \"module.exports = \" > supportedBrowsers.js; browserslist-useragent-regexp --allowHigherVersions >> supportedBrowsers.js"
  }
}
```
?

**Comment by shiraze** [comment]
![image](https://user-images.githubusercontent.com/9248719/62042049-03c72f00-b1f5-11e9-867e-359859f031b8.png)

**Comment by dangreen** [comment]
@shiraze try this

```json
{
  "scripts": {
    "supportedBrowsers": "(echo module.exports = && browserslist-useragent-regexp --allowHigherVersions) > supportedBrowsers.js"
  }
}
```

**Comment by shiraze** [comment]
Excellent! That worked a treat. I owe you pizza ;)
![image](https://user-images.githubusercontent.com/9248719/62048261-565c1780-b204-11e9-92e6-e1a52652a2c1.png)

**Comment by dangreen** [comment]
https://github.com/browserslist/browserslist-useragent-regexp/commit/8085e3f15cb45b6071c5d6858c133d141a53974c
