### ISSUE TITLE
Safari not detected correctly

### ISSUE THREAD

**Issue by tobyroworth** [browserslist/browserslist-useragent-regexp#432]
Running:
```
      browserlist_regexp.getUserAgentRegExp({
        browsers: "last 2 Safari versions",
        ignorePatch: true,
        ignoreMinor: true,
        allowHigherVersions: true,
        allowZeroSubverions: true
      }).toString();
```
outputs:

`/(Version\/(12|(1[3-9]|[2-9]\d|\d{3,})|13|(1[4-9]|[2-9]\d|\d{3,}))\.\d+(?:\.\d+)? Safari\/)/`

This doesn't match
"Mozilla/5.0 (iPad; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"

I think this issue is with the "Mobile..." part, which isn't accounted for in the regexp.

As a workaround I'm using the following.

`string.replace("? Safari", "? .* Safari");`

**Comment by dangreen** [comment]
@tobyroworth Hi. To match mobile safari you should use iOS queries, e. g. "last 2 iOS versions".

**Comment by tobyroworth** [comment]
@dangreen Thanks - I've found that in the [browserslist docs](https://github.com/browserslist/browserslist#browsers) now
