### ISSUE TITLE
Typo in allowZeroSubverions, lost the s

### ISSUE THREAD

**Issue by saitonakamura** [browserslist/browserslist-useragent-regexp#434]
This typo is all over the database, so i believe it needs to be fixed in a backwards-compatible manner

**Comment by dangreen** [comment]
🤦

**Comment by dangreen** [comment]
@saitonakamura Thank you for issue report.

> to be fixed in a backwards-compatible

I think no one has used this option before. As an option I can do a major release with fix. Your thoughts?

**Comment by saitonakamura** [comment]
> I think no one has used this option before. As an option I can do a major release with fix. Your thoughts?

I believe your know your users better than me, so it's your call 🙂I was just being defensive

**Comment by dangreen** [comment]
@saitonakamura fixed in [v2.0.5](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v2.0.5)
