### ISSUE TITLE
ChromeAndroid query aren't correct

### ISSUE THREAD

**Issue by saitonakamura** [browserslist/browserslist-useragent-regexp#480]
If you use something like `last 10 ChromeAndroid versions`, it isn't handled properly (Chrome *version regex* Mobile)
Instead it outputs version 80 without Mobile suffix

```
~/code/browserslist-useragent-regexp % node lib/cli.js "last 10 ChromeAndroid versions" 
/((Chromium|Chrome)\/80\.0(?:\.\d+)?)/
```

Desktop chrome query handles versions correctly

```
 ~/code/browserslist-useragent-regexp % node lib/cli.js "last 10 Chrome versions"
/((Chromium|Chrome)\/(7[2-9]|8[0-1])\.0(?:\.\d+)?)/
```

**Comment by dangreen** [comment]
Hi!

Currently browserslist-useragent-regexp doesn't separate mobile and desktop browsers.

**Comment by saitonakamura** [comment]
Good to know, thanks
I hope I'd have some time to try and support it. How would you estimate the complexity of it?

**Comment by ericvoshall** [comment]
Are there any plans to add in support for separating mobile and desktop browsers?

**Comment by dangreen** [comment]
@ericvoshall Yes

**Comment by dangreen** [comment]
@saitonakamura @ericvoshall Hi. Please try [v4.0.0-beta.0](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v4.0.0-beta.0).
