### ISSUE TITLE
Wrong support for new Ms Edge based on Chromium

### ISSUE THREAD

**Issue by DOrlov77** [browserslist/browserslist-useragent-regexp#508]
In a new Edge the userAgent name is "Edg", not "Edge".
So your scripts is ignoring the Edge query but use Chrome query fo both.

**Comment by dangreen** [comment]
@DOrlov77 Hi! All Chrome-based browsers are detected as Chrome.

**Comment by DOrlov77** [comment]
Hi.
But that is exactly a defect!
Opera is also based on Chromium.

Say I have `.browserslistrc` like:
```
Chrome > 70
Edge > 82
Opera > 67
```
So running `npx browserslist` I will receive:
```
chrome 85
chrome 84
// ... cutted the list
chrome 52
chrome 51
edge 85
edge 84
edge 83
opera 71
opera 70
opera 69
opera 68
```
As you may see the `browserslist` knows about versions of Edge and Opera, but I have no chance to filter out unwanted versions of these browsers...

**Comment by dangreen** [comment]
@DOrlov77 currently browserslist-useragent-regexp is more like "engine-list", to work with engine web-platform feature.

**Comment by DOrlov77** [comment]
@dangreen probably, you want to say: "without engine web-platform features detection"?
Right now you parse browserslist result into regex in the straightforward way.
Detection means: 
or move all detected browsers to one by engine, say Chrome, Edge >= 79, Opera > ? ==> Chrome, Edge < 79 ==> Edge;
or make it granually, like Chrome => Chrome
                                         Edge < 79 ==> Edge
                                         Edge >=79 ==> Edg
                                         Opera ==> Opr
...
Anyway - I like your tool and will, probably, use it in my project.
Thank you!

**Comment by dangreen** [comment]
@DOrlov77 "to detect engine web-platform features", example: [bdsl-webpack-plugin](https://github.com/TrigenSoftware/bdsl-webpack-plugin)

I see more and more issues with vendor detection (not engine), so I think to add new flag to toggle vendor/engine mode soon.

**Comment by ajbeaven** [comment]
I'm seeing Microsoft Edge on Android not match the generated regex having been updated 5 days ago. My assumption is, if all Chrome-based browsers are being detected as Chrome (as per [comment above](https://github.com/browserslist/browserslist-useragent-regexp/issues/508#issuecomment-696635506)) then this should pass.

Here's my .browerslistrc file
```
defaults
unreleased versions
```

I'm running the following script to generate the regex script:
```
(echo export default && browserslist-useragent-regexp --allowHigherVersions --ignorePatch --ignoreMinor) > ./src/js/_SupportedBrowsers.js
```

**Comment by dangreen** [comment]
@ajbeaven Hi! Can you please provide user agent of Microsoft Edge on Android ?

**Comment by ajbeaven** [comment]
```
Mozilla/5.0 (Linux; Android 10; M2007J20CG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/46.05.4.5158
```

**Comment by dangreen** [comment]
@ajbeaven Hi. You can try [v4.0.0-beta.0](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v4.0.0-beta.0), but anyway, browserslist does provide info about Edge Desktop, not Android, so regex for Edge will match only desktop useragents.
