### ISSUE TITLE
ESModules versoin of supportedBrowsers script

### ISSUE THREAD

**Issue by hata6502** [browserslist/browserslist-useragent-regexp#553]
JavaScript (Change .js -> .ts for TypeScript)
```
    "supportedBrowsers": "echo \"const supportedBrowsers = $(browserslist-useragent-regexp --allowHigherVersions);\n\nexport { supportedBrowsers };\" > supportedBrowsers.js",
```

Usage
```
import { supportedBrowsers } from './supportedBrowsers';
```

**Comment by dangreen** [comment]
@hata6502 Hi.

1. It is just an example, you can write your own npm script if you want.
2. For [v4.0.0-beta.0](https://github.com/browserslist/browserslist-useragent-regexp/releases/tag/v4.0.0-beta.0), the example was updated to generate esm file.

**Comment by hata6502** [comment]
Thank you!
