### ISSUE TITLE
Question: which .browserslistrc file is used in monorepo?

### ISSUE THREAD

**Issue by tommueller** [browserslist/browserslist-useragent-regexp#560]
I am using a nx-monorepo containing several Angular projects. Each project contains its own .browserslistrc file. The folder-structure looks like this:
```
apps\
   app1\
      .browserslistrc
      ...
   app2\
      .browserslistrc
      ...
package.json
```

Running the tool from the repositories root folder, does generate an output. Does it actually use one of .browserslistrc files and if so, which of the two? Or does it have a build it default, if it does not find a file in the projects root?

Thanks for clarification!

**Comment by dangreen** [comment]
@tommueller Hi!

>  Does it actually use one of .browserslistrc files 

No.

> does it have a build it default, if it does not find a file in the projects root

Yes.

**Comment by tommueller** [comment]
Any chance to tell it which file to use? I couldn't find any option for the CLI tool?!

**Comment by dangreen** [comment]
You can environment variable `BROWSERSLIST_CONFIG`

https://github.com/browserslist/browserslist#environment-variables

But I think better is create `.browserslistrc` file in monorepo root.

**Comment by tommueller** [comment]
Thanks.
