### ISSUE TITLE
Error: Unexpected argument "‑‑allowHigherVersions=true"

### ISSUE THREAD

**Issue by aladdin-add** [browserslist/browserslist-useragent-regexp#60]
![image](https://user-images.githubusercontent.com/13050025/62437413-ab081100-b775-11e9-824e-cdf2c92bd0b6.png)

**Comment by aladdin-add** [comment]
it also happens in browserslist-useragent-regexp@1.3.1-beta

**Comment by dangreen** [comment]
--allowHigherVersions without =true

пн, 5 авг. 2019 г. в 10:43, 薛定谔的猫 <notifications@github.com>:

**Comment by aladdin-add** [comment]
thanks for the quick response, I've tried it, but got same error:
![image](https://user-images.githubusercontent.com/13050025/62440637-97fc3d80-b783-11e9-9eba-5188d98e4956.png)

**Comment by dangreen** [comment]
@aladdin-add 
I can't reproduce it on my side.

Can you edit `/Users/weiran/.npm-global/lib/node_modules/browserslist-useragent-regexp/lib/cli.js`?

After `var src = require('./');` paste `console.log(argueCli.argv);`
Before `const query = argueCli.argv.length ? argueCli.read() : undefined;` paste  paste `console.log(argueCli.argv);`

Run it again and send screen with result here, ok?

**Comment by aladdin-add** [comment]
the weird thing is it's working when re-run the command. not sure what happened …（⊙＿⊙；）…
![image](https://user-images.githubusercontent.com/13050025/62441678-a8aeb280-b787-11e9-9bd5-3165e82e2a25.png)

**Comment by aladdin-add** [comment]
closing as it seems working as expected.

maybe the docs can be updated to say the usage of cli options. :)
