### ISSUE TITLE
ios_saf doesn't match

### ISSUE THREAD

**Issue by florian-milky** [browserslist/browserslist-useragent-regexp#680]
In the list returned by browserslist:

ios_saf 14.5
ios_saf 14.0-14.4

The regex generated by
```
getUserAgentRegExp({
    allowHigherVersions: true,
  })
```
didn't match the user agent of these devices

**Comment by dangreen** [comment]
@florian-milky Hi! Can you please provide useragent examples and generated regexp ?

**Comment by florian-milky** [comment]
@dangreen I was pasting everything here and testing again at the same time and it turns out that my issue is different.
Instead of generating a file, I inject the regexp as an environment variable, but when sending it to the client, the serialization didn't work correctly.
Somehow it worked enough for Chrome but not for some other browsers...
