### ISSUE TITLE
Generate from string

### ISSUE THREAD

**Issue by evilPaprika** [browserslist/browserslist-useragent-regexp#884]
Is it possible to generate regex passing browserlist as a string(or object)? Using browserlistrc file not always convenient or suitable. 😞

**Comment by dangreen** [comment]
@evilPaprika  Hi!

Yes, you can.

https://github.com/browserslist/browserslist-useragent-regexp#cli

for example:

```
yarn exec -- browserslist-useragent-regexp "defaults, unreleased versions"
```

**Comment by evilPaprika** [comment]
@dangreen 
Well, I meant in javascript, not as cli utility.
I apologize for not being clear.

**Comment by dangreen** [comment]
@evilPaprika 

https://github.com/browserslist/browserslist-useragent-regexp#options

`getUserAgentRegExp(options)` method accepts `browsers` option

```ts
getUserAgentRegExp({
  browsers: "defaults, unreleased versions",
  allowHigherVersions: true,
  allowZeroSubversions: true
})
```

**Comment by evilPaprika** [comment]
omg thank you so much! 🙏 
exactly what I need!
